# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# Note: Running the CI script for each and every change is not meaningful. If we
#       would developed in feature branches only, and merge into the main branch only
#       once in a while, this would be ok, but since we all commit permanently to
#       'master' this CI script is a major energy and resource eater. So, instead, we
#       run it once every night and be happy with it.
#       Actually, since we have a Jenkins job running for all major OSes, there is
#       no need for CI integration in github anylonger, so we may just drop it.

# Run 6 o'clock in the morning...
on:
  schedule:
    - cron: '0 6 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: build
      run: (cd build/cmake; ./build.sh 6 no-gui)

